---
- name: Ensure required directories exists.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ neovim_base_dir }}"
    - "{{ neovim_config_dir }}"
    - "{{ neovim_plugins_dir }}"

- name: Install system-level packages.
  ansible.builtin.import_tasks: "system.yml"
  when: neovim_install_system_packages

- name: Set up LSP
  ansible.builtin.import_tasks: "lsp.yml"
  when: neovim_use_lsp

- name: Set up TreeSitter
  ansible.builtin.import_tasks: "treesitter.yml"
  when: neovim_use_treesitter

- name: Install config files
  ansible.builtin.import_tasks: "config.yml"

- name: Install plugins.
  ansible.builtin.import_tasks: "plugins.yml"
