---
- name: Copy plugin configuration files.
  ansible.builtin.template:
    src: "templates/lua/plugins/{{ item['config']['name'] }}.lua.j2"
    dest: "{{ neovim_plugins_dir }}/{{ item.config['name'] }}.lua"
    mode: "0644"
  loop: "{{ neovim_plugins }}"
  when: item.enabled and item.config is defined

- name: Ensure that packer is installed.
  when: neovim_plugin_manager == "packer"
  notify: PackerSync
  block:
    - name: Clone packer repo.
      ansible.builtin.git:
        repo: https://github.com/wbthomason/packer.nvim
        dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
        depth: 1
        version: master

    - name: Install packer configuration templates
      ansible.builtin.template:
        src: templates/lua/plugins/packer.lua.j2
        dest: "{{ neovim_plugins_dir }}/packer.lua"
        mode: "0644"
        force: true

- name: Ensure that lazy is installed.
  when: neovim_plugin_manager == "lazy"
  block:
    - name: Install lazy configuration templates
      ansible.builtin.template:
        src: templates/lua/plugins/lazy.lua.j2
        dest: "{{ neovim_plugins_dir }}/lazy.lua"
        mode: "0644"
        force: true
