---
# tasks file for fonts
- name: Check if fonts already exist.
  ansible.builtin.stat:
    path: "{{ fonts_dir }}/{{ item }}"
  register: existing_fonts
  loop: "{{ fonts_nerdfonts_fonts }}"

- name: Include nerdfont tasks.
  ansible.builtin.include_tasks: nerdfonts.yml
  loop: "{{ fonts_nerdfonts_fonts }}"
  loop_control:
    index_var: index
  when: not existing_fonts.results[index].stat.exists

- name: Check if CJK fonts are installed
  ansible.builtin.stat:
    path: "{{ fonts_dir }}/{{ fonts_cjk_dirname }}"
  register: stat_noto_cjk

- name: Ensure CJK fonts are installed.
  when: not stat_noto_cjk.stat.exists
  become: true
  block:
    - name: Install CJK fonts.
      community.general.pacman:
        name: "{{ fonts_cjk_package }}"
        state: present

    - name: Copy fonts to {{ fonts_dir }}
      ansible.builtin.copy:
        src: /usr/share/fonts/{{ fonts_cjk_dirname }}
        dest: "{{ fonts_dir }}"
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        remote_src: true

    - name: Remove CJK fonts.
      community.general.pacman:
        name: "{{ fonts_cjk_package }}"
        state: absent
