---
# tasks file for fonts
- name: Check if fonts already exist.
  ansible.builtin.stat:
    path: "{{ fonts_dir }}/{{ item }}"
  register: existing_fonts
  loop: "{{ fonts_nerdfonts_fonts }}"

- name: Include nerdfont tasks.
  ansible.builtin.include_tasks: nerdfonts.yml
  loop: "{{ fonts_nerdfonts_fonts }}"
  loop_control:
    index_var: index
  when: not existing_fonts.results[index].stat.exists

- name: Ensure CJK fonts are installed.
  become: true
  block:
    - name: Install CJK fonts.
      community.general.pacman:
        name: noto-fonts-cjk
        state: present

    - name: Copy fonts to ~/.local/share/fonts.
      ansible.builtin.copy:
        src: /usr/share/fonts/noto-cjk
        dest: /home/{{ ansible_user }}/.local/share/fonts/
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        remote_src: true

    - name: Remove CJK fonts.
      community.general.pacman:
        name: noto-fonts-cjk
        state: absent
