---
- name: Remove uneeded directories.
  ansible.builtin.file:
    name: "{{ item }}"
    state: absent
  loop:
    - ~/Music
    - ~/Documents
    - ~/Desktop
    - ~/Pictures
    - ~/Public
    - ~/Templates
    - ~/Videos

- name: Ensure directories exist.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "~/code/www"
    - "~/code/go"
    - "~/code/servers"
    - "~/code/roles"

- name: Create soft links.
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: ~/Nextcloud/Documents, dest: ~/Documents }
    - { src: ~/Nextcloud/Design, dest: ~/Design }
    - { src: ~/Nextcloud/Notes, dest: ~/Notes }
