---
- name: Add a host in the configuration
  community.general.ssh_config:
    user: "{{ ansible_user }}"
    host: "{{ item.host }}"
    remote_user: "{{ item.remote_user | default(ansible_user) }}"
    hostname: "{{ item.hostname | default(omit) }}"
    port: "{{ item.port | default(438) }}"
    proxyjump: "{{ item.proxyjump | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ ssh_config_hosts }}"
