---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: archlinux
    image: docker.io/library/archlinux:latest
    pre_build_image: false
    dockerfile: ./Dockerfile.j2
provisioner:
  name: ansible
verifier:
  name: ansible
