---
- name: Create dev test container.
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    dev_container_image_name: localhost/dev/dev
    dev_container_image_tag: latest
    dev_container_name: dev-test
    dev_container_home: /home/pl/box/dev/test
    dev_container_autostart: false

  tasks:
    - name: Include role dev_container.
      ansible.builtin.include_role:
        name: dev_container

- name: Provision dev-test
  hosts: dev-test

  roles:
    - { role: fonts, tags: ["fonts"] }
    - { role: ohmyzsh, tags: ["ohmyzsh"] }
    - { role: neovim, tags: ["neovim"] }
