---
- name: Provision dev
  hosts: dev

  roles:
    - { role: palekiwi.dotfiles, tags: dotfiles }
    - { role: fonts, tags: fonts }
    - { role: ohmyzsh, tags: ohmyzsh }
    - { role: neovim, tags: neovim }
    - { role: gtk, tags: gtk }

  tasks:
    - name: Tasks/packages.
      ansible.builtin.import_tasks: ./tasks/packages.yml
      tags: packages

    - name: Tasks/hosts.
      ansible.builtin.import_tasks: ./tasks/hosts.yml
      tags: hosts

    - name: Tasks/dirs.
      ansible.builtin.import_tasks: ./tasks/dirs.yml
      tags: dirs

    - name: Tasks/pip.
      ansible.builtin.import_tasks: ./tasks/pip.yml
      tags: pip

    - name: Tasks/distrobox.
      ansible.builtin.import_tasks: ./tasks/distrobox.yml
      tags: distrobox

    - name: Tasks/systemd.
      ansible.builtin.import_tasks: ./tasks/systemd.yml
      tags: systemd
